# Generated by Django 5.2.1 on 2025-06-13 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='djangos/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('DJ', 'Django'), ('DF', 'Django Rest Framework'), ('DM', 'Django CMS'), ('DC', 'Django Channels')], default='DJ', max_length=2)),
            ],
        ),
    ]
