# Generated by Django 5.2.1 on 2025-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangovariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
