# Generated by Django 5.2.1 on 2025-06-17 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotutorial', '0002_djangovariety_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_number', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='djangotutorial.djangovariety')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('django', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='djangotutorial.djangovariety')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('django_varieties', models.ManyToManyField(related_name='stores', to='djangotutorial.djangovariety')),
            ],
        ),
    ]
